name: "ShellCheck workflow"

on:
  workflow_run:
    workflows:
      - "Main workflow" 
    types: 
      - completed
    branches:
      - '**'

jobs:
  run-shellcheck:
    name: ShellCheck on test success
    runs-on: ubuntu-latest
    steps:
      - name: Install ShellCheck
        run: |
          sudo apt-get install shellcheck

      - name: Run ShellCheck
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
        run: |
          cd ~/try            
          shellcheck ./try -S warning 
