name: ShellCheck workflow
  
on:
  workflow_run:
    workflows:
      - "Main workflow" 
    types: 
      - completed

jobs:
  on-success:
    name: ShellCheck on test success
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Install ShellCheck
        run: |
          sudo apt-get install shellcheck

      - name: Run ShellCheck
        run: |
          cd ~/try            
          shellcheck ./try -S warning 
