name: ShellCheck workflow
  
on: 
  pull_request:
  push:
  schedule:
    - cron: '17 14 * * *'

jobs:
  shellcheck:
    strategy:
      fail-fast: false
        
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Install dependencies
        run: |
          uname -a
          sudo apt-get update
          sudo apt-get install shellcheck

      - name: Checkout
        uses: actions/checkout@v2 
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Run ShellChecks
        run: |
          cd ..
          cp -r try ~
          cd ~/try            
          shellcheck ./try -S warning 
