name: Vagrant
  
on: 
  pull_request:
  push:
  schedule:
    - cron: '17 14 * * *'

jobs:
  debian:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start vagrant box
        run: vagrant up debian

  debianrustup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start vagrant box
        run: vagrant up debianrustup

  debianlvm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start vagrant box
        run: vagrant up debianlvm

  rocky9:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start vagrant box
        run: vagrant up rocky9

  fedora33:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start vagrant box
        run: vagrant up fedora33
