name: Vagrant
  
on: 
  pull_request:
  push:
  schedule:
    - cron: '17 14 * * *'

jobs:
  vagrant:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Show Vagrant version
        run: vagrant --version

      - name: Run vagrant up
        run: vagrant up

      - name: ssh into box after boot
        run: vagrant ssh -c "echo 'hello world!'"
