name: Distro and LVM tests
  
on:
  push:
    branches:
    - main
  pull_request:

strategy:
  matrix:
    vagrant_target:
      - debian
      - debianrustup
      - debianlvm
      - rocky9
      - fedora33

jobs:
  vagrant:
    strategy:
      matrix:
        vagrant_target:
          - debian
          - debianrustup
          - debianlvm
          - rocky9
          - fedora33
    runs-on: macos-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
         
      - name: Run VM in Vagrant
      - run: vagrant up ${{ matrix.vagrant_target }}
