name: Distro and LVM tests
  
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  vagrant:
    strategy:
      matrix:
        vagrant_target:
          - debian
          - debianrustup
          - debianlvm
          - rocky9
          - fedora33
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start vagrant box
        run: vagrant up ${{ matrix.vagrant_target }}
