name: Vagrant VM tests

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  vagrant:
    # These tests need the self-hosted runner, which is not always available.
    # Opt in by putting [vagrant] in the commit message (to main) or PR title.
    # Putting [vagrant] in the commit message on a PR will _not_ run this pipeline.
    if: contains(github.event.head_commit.message, '[vagrant]') || contains(github.event.pull_request.title, '[vagrant]')
    strategy:
      fail-fast: false
      matrix:
        vagrant_target:
          - debian
          - debianrustup
          - debianlvm
          - rocky9
          - fedora39
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup
        run: bash /home/runner/cleanup.sh

      - name: Start vagrant box
        run: vagrant up ${{ matrix.vagrant_target }}

      - name: Stop vagrant box
        run: vagrant destroy -f ${{ matrix.vagrant_target }}
        if: ${{ success() || failure() }} # we want to run this step even if the last step failed
